### ISSUE TITLE
Different weights

### ISSUE THREAD

**Issue by vincentarelbundock** [ngreifer/fwb#4]
Not sure if useful, but I just read this on Twitter:

https://twitter.com/lihua_lei_stat/status/1640017297216622592

> Shao and Tu (1995) recommended Gamma(4,1) weights which yield second-order accuracy for mean functionals. They are better than Exp(1), namely Gamma(1,1), in terms of frequentist properties.

**Comment by ngreifer** [comment]
Interesting suggestion. That should be pretty easy to implement.

**Comment by ngreifer** [comment]
Done in the new version. I added Mammen weights, which are second-order accurate and related to the wild bootstrap, multinomial weights, which yield identical results to using the ordinary resampling bootstrap, and Poisson weights, which are similar to multinomial weights but a little faster to generate. The Gamma weights turned out to be very specific and not amenable to use in general contexts. The Mammen weights have their desired properties, anyway (positive; mean, SD, and skew all equal to 1).

The type of weights can be specified using the `wtype` argument to `fwb()` or by setting a global default using `set_fwb_wtype()`.

**Comment by vincentarelbundock** [comment]
Very cool!
